### ISSUE TITLE
Adium build in 2021

### ISSUE THREAD

**Issue by Neustradamus** [adium/adium#14]
It is planned to have an update in 2021?

Pidgin has been updated since last Adium version...

Linked to:
- https://github.com/adium/adium/issues/2

**Comment by Asher-** [comment]
I've edited, cleaned up, and re-opened your prior post to use as a reference.

**Comment by Neustradamus** [comment]
@RobFog, @Asher-: Can you reopen this ticket, the last build is very old 1.5.8 on 2013-10-13:
- https://github.com/adium/adium/tags
