### ISSUE TITLE
Recover Contributing Guidelines

### ISSUE THREAD

**Issue by Asher-** [adium/adium#21]
Previously linked from trac. Someone has the content somewhere?

**Comment by RobFog** [comment]
Here are some relevant pages:
* "Development": https://web.archive.org/web/20200915230142/https://trac.adium.im/wiki/Development
* "ContributingCode": https://web.archive.org/web/20200923043011/https://trac.adium.im/wiki/ContributingCode
* "User Interface Design Guidelines": https://web.archive.org/web/20200923043702/https://trac.adium.im/wiki/UIDesignGuidelines
* "Tips and Tricks for Coding on Adium (and in general)": https://web.archive.org/web/20200923044150/https://trac.adium.im/wiki/DevelopmentTipsAndTricks
* "Coding Style Guidelines" (from 2017): https://web.archive.org/web/20170306235100/https://trac.adium.im/wiki/CodingStyle

**Comment by estella144** [comment]
Yep. They all lead back to the right pages. Modify those links and we can consider this closed.

**Comment by Asher-** [comment]
I believe things should be correct now. Please verify and let me know if not.
