### ISSUE TITLE
Cannot change IRC nickname once mistyped

### ISSUE THREAD

**Issue by estella144** [adium/adium#22]
There is no option to change the nick that you connect through Adium with. Even if you _change_ it using the necessary window, it still changes back once connected.

**Comment by ChrisForsythe** [comment]
Can you delete and re-add the account and see if it has the same problem?

**Comment by estella144** [comment]
@ChrisForsythe I can't delete an account.

**Comment by ChrisForsythe** [comment]
> @ChrisForsythe I can't delete an account.

Umm.. you cannot go into Adium preferences and delete and recreate the account?

**Comment by estella144** [comment]
@ChrisForsythe now it works, but I cannot connect to any IRC channels - see #28 .

**Comment by estella144** [comment]
We can consider this closed.
