### ISSUE TITLE
Cannot connect to any IRC channels

### ISSUE THREAD

**Issue by estella144** [adium/adium#28]
Using Adium 1.5.10.4, when I press the IRC icon, it does nothing.

**Comment by RobFog** [comment]
Works fine here.

We need a more detailed description of the problem. I don't even know what you mean by "IRC icon".

**Comment by estella144** [comment]
https://user-images.githubusercontent.com/80313321/110655826-4dd90a80-81b7-11eb-8c32-3022dca4f564.mov

**Comment by estella144** [comment]
That is the problem @RobFog.

**Comment by RobFog** [comment]
That is not how joining a channel works in Adium.

Please have a look at our extensive documentation before rushing to report a "bug": https://adium.im/help/pgs/AdiumDocumentation.html

**Comment by estella144** [comment]
@RobFog got it.
