### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by cake03** [adium/adium#35]
Adium is very useful, but even though there are a lot of commits, the latest release is **WAY** outdated and does not have the latest features used by it.

**Comment by RobFog** [comment]
We have milestones for planned releases. See https://github.com/adium/adium/milestones.

 #2 was closed previously.

**Comment by Neustradamus** [comment]
@RobFog: Can you reopen this ticket, the last build is very old 1.5.8 on 2013-10-13:
- https://github.com/adium/adium/tags
