### ISSUE TITLE
Adium scrolling bug  in macOS Catalina And Big Sur

### ISSUE THREAD

**Issue by TarunJohar** [adium/adium#36]
Adium has a scrolling bug on **macOS Catalina** (version 10.15) and **macOS Big Sur** (version 11).  When the message window is scrolled back and a new message arrives, the window does not scroll to the bottom.

The Template.html in the latest master does not resolve the issue.  The attached Template.html has the fix, tested on Catalina and Big Sur.

**NOTE:** Rename attached [Template.txt](https://github.com/adium/adium/files/6562051/Template.txt) to Template.html

**Comment by RobFog** [comment]
Fixed in master.

**Comment by TarunJohar** [comment]
Thanks for the quick turnaround @RobFog 

Can you share if your team could please release 1.5.11 with the various fixes in master?  

It has been a long time since 1.5.10 and the open issues for 1.6.0 suggest that it might be some time before the 1.6.0 release is ready.

**Comment by ChrisForsythe** [comment]
> Thanks for the quick turnaround @RobFog 
> 
> 
> 
> Can you share if your team could please release 1.5.11 with the various fixes in master?  
> 
> 
> 
> It has been a long time since 1.5.10 and the open issues for 1.6.0 suggest that it might be some time before the 1.6.0 release is ready.

Realistically we have 1 developer. He's spending his time on this where he can. If a new release isn't out then it's not ready. 

We have no timeline for the next release.
