### ISSUE TITLE
A migration from hg.adium.im

### ISSUE THREAD

**Issue by Neustradamus** [adium/adium#4]
I think it is time to migrate all from https://hg.adium.im/ to here and/or in a GitLab (self-hosted or hosted on gitlab.com).

It will permit a better development of Adium.

Note: It is easy to do automatic mirroring between GitHub and GitLab like a lot of projects/organizations/companies.

**Comment by jas8522** [comment]
hg isn't even live anymore and nobody has stepped up to do this... why create more work that nobody wants to do?

**Comment by RobFog** [comment]
Jordan, I think this report is from a time when this repo was not the main repo but a mirror. So take it as a suggestion to move to Github which has since been done. ;-)
