### ISSUE TITLE
ADIUM PROBLEM since creation

### ISSUE THREAD

**Issue by edithzakharova5** [adium/adium#51]
This Adium problem is since the day 1 of its creation. I always have to fucking scroll to be able to see the messages I receive on jaberrrr whyyyyyy whyyy why why why why ? Now it's not even working anymore to scroll fast it has a lot of bugs why you never repair this ???

**Comment by RobFog** [comment]
Duplicate of #36

Adium development has been inactive for a while. That is why the fix for the scrolling bug has not been released as part of a new version of Adium.
