### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by ghost** [adium/adium#9]
I think this project is dead. Am I right? Or does it worth to ask if Apple M1 will be supported? :D

**Comment by donatj** [comment]
I've had an eye on it for a while and am watching the repo.

They _just recently_ moved here from Bitbucket, hence your issue being #9 on a 20 year old program.

There have been little minor flurries of activity. I don't expect new features, but I expect some minor maintenance in the near future.

**Comment by RobFog** [comment]
To my knowledge, nobody has been working on Adium for a while. @Asher- was the last I know.

**Comment by Asher-** [comment]
I am working on it in fits and starts. I haven't yet gotten things in order to push a new release. Hopefully I will be able to do so soon, but things keep getting in the way. 

If anyone else wanted to get involved, I would be happy to find time to coordinate.

**Comment by ghost** [comment]
Hey guys, thank you for the answers. Looking forward to the new versions ...

**Comment by Neustradamus** [comment]
Master branch is very very very old: 5 Sep 2016, in few days: 4 years, 5 months.

**Comment by ChrisForsythe** [comment]
If this is an easy fix, do it in 1.6. If not, punt to 1.7.

**Comment by estella144** [comment]
@ChrisForsythe are you sure this is an _easy_ fix? Adding support for another processor is not going to be easy. (By the way, I have got one of the newest MacBooks and it does not contain an M1.)

**Comment by Asher-** [comment]
I don't have an m1 and haven't tried compiling anything on one yet, but from what I've heard it shouldn't be an issue. 

It's not really adding a processor— just making sure that it compiles and works as expected, and Apple has done a lot of work on the toolchain to ensure that.

**Comment by estella144** [comment]
@Asher- Well, who has an M1, then?

**Comment by jas8522** [comment]
@estella144 it shouldn't matter, from what I understand. My understanding is that newer versions of XCode will allow cross compiling for M1 CPUs. But to make that work, there needs to be a new release, so this issue blocks on #2

**Comment by Asher-** [comment]
This issue is identical with #2 AFAIC.

**Comment by estella144** [comment]
@Asher- and @jas8522 it is not. AFAIC #2 is just about getting Adium 1.5.11 out, while this is specific, centred around Apple M1 support.

**Comment by jas8522** [comment]
> @Asher- and @jas8522 it is not. AFAIC #2 is just about getting Adium 1.5.11 out, while this is specific, centred around Apple M1 support.

I think you're missing the point. In order to support M1 we need to be able to build Adium and create a release. Once we can do that, creating a build that compiles for M1 processors *should* be as simple as checking a box in XCode and we will most definitely make that happen as soon as the project builds. Therefore this really is fundamentally the same as #2 because once it builds, it will be built for M1.

**Comment by ChrisForsythe** [comment]
> @ChrisForsythe are you sure this is an _easy_ fix? Adding support for another processor is not going to be easy. (By the way, I have got one of the newest MacBooks and it does not contain an M1.)

No, which is why I said "if it's easy, do this, if not, do this". Followed by assigning it to a milestone. Literally just trying to divvy up the work. Not all issues can be resolved in a single release.

So, if it's an easy checkbox, then yea it makes sense to go with 1.6. But if it's not easy and by easy I mean "click a checkbox" type of easy, it would make sense to punt it to another milestone. And it may get punted again. And again, etc until someone gets to it.

**Comment by Asher-** [comment]
Deploying to M1 (given everything else in order) is trivial. 

Ensuring that M1 is working and potentially debugging issues... not so trivial.

**Comment by estella144** [comment]
@Asher- no. Checking a checkbox, as @ChrisForsythe said, will require it to compile 2 times, as far as I can see.

**Comment by Asher-** [comment]
How many times do you think things get compiled while making sure code is in working order?

**Comment by estella144** [comment]
@Asher- 2 per build. 1 for Intel® processors and 1 for the M1.

**Comment by Asher-** [comment]
Identical with #2.

**Comment by estella144** [comment]
@Asher-: Er, *no*. This issue is **not** a duplicate of #2 and the discussion is **not** about the issue posed by #2.
